// import type { Metadata } from "next";
// import "./globals.css";
// import Navbar from "./components/Navbar";

// export const metadata: Metadata = {
//   title: "Project 3",
//   description: "Generated by Muhammad Nour Dabash",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body
//         style={{ backgroundColor: "#F7FAFC" }}
//         className="bg-gray-50 text-gray-800"
//       >
//         <div className="flex flex-col">
//           {/* Header */}
//           <header className="bg-white shadow-sm sticky top-0 z-50">
//             <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
//               <div className="flex justify-between items-center py-4">
//                 <h1 className="text-2xl font-extrabold text-blue-600 tracking-tight">
//                   Project 3
//                 </h1>
//                 <Navbar />
//               </div>
//             </div>
//           </header>

//           {/* Main Content */}
//           <main className="flex-1 max-w-7xl mx-auto w-full p-4 sm:p-6">
//             {children}
//           </main>

//           {/* Footer */}
//           <footer className="bg-white border-t py-4 text-center text-sm text-gray-500">
//             &copy; {new Date().getFullYear()} Project 3. Built with ❤️ using
//             Next.js.
//           </footer>
//         </div>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Project 3",
  description: "Generated by Muhammad Nour Dabash",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: "#F7FAFC" }} className="text-gray-800">
        {/* Make entire page take full height */}
        <div className="min-h-screen flex flex-col">
          {/* Header */}
          <header className="bg-white shadow-sm sticky top-0 z-50">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between items-center py-4">
                <h1 className="text-2xl font-extrabold text-blue-600 tracking-tight">
                  Project 3
                </h1>
                <Navbar />
              </div>
            </div>
          </header>

          {/* Main Content grows to push footer down */}
          <main className="flex-1 max-w-7xl mx-auto w-full p-4 sm:p-6">
            {children}
          </main>

          {/* Footer sticks to bottom if content is short */}
          <footer className="bg-white border-t py-4 text-center text-sm text-gray-500">
            &copy; {new Date().getFullYear()} Project 3. Built with ❤️ By
            Muhammad Nour Dabash using Next.js
          </footer>
        </div>
      </body>
    </html>
  );
}
