// // import type { Metadata } from "next";
// // import "./globals.css";
// // import Link from "next/link";

// // export const metadata: Metadata = {
// //   title: "Project 3",
// //   description: "Generated by Muhammad Nour Dabash",
// // };

// // export default function RootLayout({
// //   children,
// // }: {
// //   children: React.ReactNode;
// // }) {
// //   return (
// //     <html lang="en">
// //       <body className="bg-gray-50 text-gray-800">
// //         <div className="min-h-screen flex flex-col">
// //           {/* Header */}
// //           <header className="bg-white shadow-md">
// //             <div className="max-w-6xl mx-auto px-6 py-4 flex justify-between items-center">
// //               <h1 className="text-xl font-bold text-blue-600">Project 3</h1>
// //               <nav className="space-x-4">
// //                 <Link href="/" className="text-gray-700 hover:text-blue-600">
// //                   Home
// //                 </Link>
// //                 <a
// //                   href="/dashboard"
// //                   className="text-gray-700 hover:text-blue-600"
// //                 >
// //                   Dashboard
// //                 </a>
// //               </nav>
// //             </div>
// //           </header>

// //           {/* Main content */}
// //           <main className="flex-1 max-w-6xl mx-auto p-6">{children}</main>

// //           {/* Footer */}
// //           <footer className="bg-white border-t mt-6">
// //             <div className="max-w-6xl mx-auto px-6 py-4 text-center text-sm text-gray-500">
// //               &copy; {new Date().getFullYear()} Project 3. Built with ❤️ and
// //               Next.js
// //             </div>
// //           </footer>
// //         </div>
// //       </body>
// //     </html>
// //   );
// // }

// import type { Metadata } from "next";
// import "./globals.css";
// import Link from "next/link";
// import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: "Project 3",
//   description: "Generated by Muhammad Nour Dabash",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className="bg-gray-50 text-gray-800">
//         <div className="min-h-screen flex flex-col">
//           {/* Header */}
//           <header className="bg-white shadow-sm sticky top-0 z-50">
//             <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
//               <div className="flex justify-between items-center py-4">
//                 <h1 className="text-2xl font-extrabold text-blue-600 tracking-tight">
//                   Project 3
//                 </h1>
//                 <nav className="hidden md:flex space-x-6">
//                   <NavLink href="/">Home</NavLink>
//                   <NavLink href="/dashboard">Dashboard</NavLink>
//                 </nav>
//               </div>
//             </div>
//           </header>

//           {/* Main Content */}
//           <main className="flex-1 max-w-7xl mx-auto w-full p-4 sm:p-6">
//             {children}
//           </main>

//           {/* Footer */}
//           <footer className="bg-white border-t py-4 text-center text-sm text-gray-500">
//             &copy; {new Date().getFullYear()} Project 3. Built with ❤️ using
//             Next.js.
//           </footer>
//         </div>
//       </body>
//     </html>
//   );
// }

// function NavLink({
//   href,
//   children,
// }: {
//   href: string;
//   children: React.ReactNode;
// }) {
//   const pathname = usePathname();
//   const isActive = pathname === href;

//   return (
//     <Link
//       href={href}
//       className={`transition-colors duration-200 ${
//         isActive
//           ? "text-blue-600 font-semibold"
//           : "text-gray-700 hover:text-blue-600"
//       }`}
//     >
//       {children}
//     </Link>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Project 3",
  description: "Generated by Muhammad Nour Dabash",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-50 text-gray-800">
        <div className="flex flex-col">
          {/* Header */}
          <header className="bg-white shadow-sm sticky top-0 z-50">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="flex justify-between items-center py-4">
                <h1 className="text-2xl font-extrabold text-blue-600 tracking-tight">
                  Project 3
                </h1>
                <Navbar />
              </div>
            </div>
          </header>

          {/* Main Content */}
          <main className="flex-1 max-w-7xl mx-auto w-full p-4 sm:p-6">
            {children}
          </main>

          {/* Footer */}
          <footer className="bg-white border-t py-4 text-center text-sm text-gray-500">
            &copy; {new Date().getFullYear()} Project 3. Built with ❤️ using
            Next.js.
          </footer>
        </div>
      </body>
    </html>
  );
}
